### ISSUE TITLE
大佬，你的github年份有点诡异

### ISSUE THREAD

**Issue by biningo** [zhmushan/zhmushan#1]

**Comment by zhmushan** [comment]
这是因为 git 提交信息完全是在本地写的, 所以只要把系统时间改成 1990 年, 提交一行代码就好了.....

**Comment by biningo** [comment]
这不算bug吧。。。。
我说呢！90年连github都没有 哈哈哈哈   
强！

**Comment by zhmushan** [comment]
偷偷告诉你一个秘密, 我其实是 GitHub 创始人的小号

**Comment by biningo** [comment]
哈哈哈哈哈哈
